# Generated by Django 6.0.2 on 2026-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('1month', '1 Month'), ('3month', '3 Months'), ('6month', '6 Months')], default='1month', max_length=20),
        ),
    ]
